identifier: l42e0cq121j07f17
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: luna
homeFolder: C:\Users\Sh00n3\Desktop\luna
distFolder: dist/luna
outDir: C:\Users\Sh00n3\Desktop\luna\docs
handle404: ''
allowErrorCollect: true
